@startuml  
skinparam {
    linetype ortho
    ArrowColor SeaGreen
}

package processes{
    interface Process{}

    class Bcra{}
    class Bna{}
    class Sap{}

    abstract Log{}

    class LogTxt{}
    class LogXlsx{}
}

interface SettingService{}
class SettingSap{}
class SettingBna{}
class SettingBcra{}

Process <|.. Bcra
Process <|.. Bna
Process <|.. Sap
Process <|.. Log

Log <|.. LogTxt
Log <|.. LogXlsx

SettingService <|.. SettingSap
SettingService <|.. SettingBna
SettingService <|.. SettingBcra

@enduml